version: '3.8'

services:
  blockmesh-cli:
    image: blockmesh/blockmesh-cli:latest
    container_name: blockmesh-cli
    environment:
      - EMAIL=${USER_EMAIL}
      - PASSWORD=${USER_PASSWORD}
    restart: unless-stopped
